# Файлы/папки, которые SwiftLint должен проверять
included:
  - MemeFortuneTeller
  - MemeFortuneTellerTests

# Отключённые правила
disabled_rules:
  - trailing_whitespace
  - line_length
  - force_cast

# Включаем opt-in правила (неактивны по умолчанию)
opt_in_rules:
  - empty_count
  - fatal_error_message
  - force_unwrapping

# Игнорировать определённые пути (например, сторонние библиотеки или сгенерированный код)
excluded:
  - Pods
  - Carthage
  - Generated
